### ISSUE TITLE
Compatibility Warp10 3.0

### ISSUE THREAD

**Issue by miton18** [CleverCloud/erlenmeyer#1]
In order to works with Warp10 v3.0

we need to:
* drop AUTHENTICATE calls

calls can be found here:

erlenmeyer/core/mc2.go: b.WriteString("$token AUTHENTICATE \n")
erlenmeyer/proto/opentsdb/query.go:             fmt.Fprintf(out, "DUP AUTHENTICATE 20000000 LIMIT\n")
erlenmeyer/proto/influxdb/query.go:     mc2 := fmt.Sprintf("'%s' AUTHENTICATE\n", token)
erlenmeyer/proto/influxdb/query.go:     AUTHENTICATE

**Comment by StevenLeRoux** [comment]
Fixed in #2 closing
